### ISSUE TITLE
Search bar above left nav is missing

### ISSUE THREAD

**Issue by brian-armory** [google/docsy-example#88] opened 2020-12-01 19:18 UTC
For https://example.docsy.dev/, the search bar above the toc is set.

 (https://github.com/google/docsy-example/blob/3cbe73a93a413872774e8115aa3641f1472bc51a/config.toml#L133).

The search bar doesn't appear above the toc though:
https://s.armory.io/qGulz4dW

We ran into this issue on our docs site (docs.armory.io) and are planning to downgrade the theme version since it worked previously.

**Comment by LisaFC** [comment] 2020-12-11 11:09
Duplicate of https://github.com/google/docsy/issues/384 (we'll close out that one when the issue is fixed)

**Closed by LisaFC** 2020-12-11 11:09 UTC
