### ISSUE TITLE
fatal error: pipe failed

### ISSUE THREAD

**Issue by kstirto** [google/docsy-example#84] opened 2020-11-13 01:30 UTC
This is my Hugo version:
`Hugo Static Site Generator v0.78.1/extended darwin/amd64 BuildDate: unknown`

After cloning and running a local copy (`hugo server`) I received the following error:
[Docsy-Error.txt](https://github.com/google/docsy-example/files/5534157/Docsy-Error.txt)

I tried with the following command and it works, no error. I could see the site in localhost:1313.
`hugo server --watch=false`

Could anyone help resolving this issue please? Thanks

**Comment by LisaFC** [comment] 2020-12-11 11:11
Duplicate of #89 

It seems to be a Hugo issue with sites with lots of images (though this site doesn't have that many images, so I'm not sure why). Can you keep running with the --watch=false flag for now until Hugo get this sorted?

**Closed by LisaFC** 2020-12-11 11:11 UTC

**Comment by LisaFC** [comment] 2020-12-11 11:26
(I agree that running with watch=false isn't ideal as it means you need to rebuild your site to preview but hopefully Hugo will come up with a fix)

**Comment by LisaFC** [comment] 2021-01-12 10:53
See the duplicate issue for a Mac workaround, btw.
