### ISSUE TITLE
Section Menus behave unpredictably

### ISSUE THREAD

**Issue by mgibson323** [google/docsy-example#68] opened 2020-08-03 20:41 UTC
When trying to create nested section menu items, the menu items still show in the main menu as well as the new nested location. You can see this on the example site, too: 

<img width="536" alt="Screen Shot 2020-08-03 at 1 37 56 PM" src="https://user-images.githubusercontent.com/4676632/89225192-ac3d6b00-d58e-11ea-81f8-243db9e16970.png">

I'm not sure how to fix this myself, which is why I decided to open an issue to report the behavior. 

Current behavior: Items nested in the menu show also on the main menu, so are showing twice.

Desired behavior: Items nested in the menu should show only in the nested location and not also on the main menu.

**Comment by LisaFC** [comment] 2020-08-18 12:23
That is very odd. It's not currently happening on the live example site so may have been a transient issue: https://example.docsy.dev/docs/tasks/ponycopters/configuring-ponycopters/

Can you check if it's still happening for you?

**Comment by LisaFC** [comment] 2020-08-24 15:22
Closing this as I can't reproduce it, please reopen if it happens again.

**Closed by LisaFC** 2020-08-24 15:22 UTC

**Comment by mgibson323** [comment] 2020-08-31 20:14
Hi @LisaFC sorry for late response, I was not able to reproduce it on my own project either, but thought I'd report what I saw anyway. Thank you!
